name: paleophysio
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - jupyterlab=2.1
  - numpy
  - pip
  - seaborn
  - pandas
  - scipy
  - compilers
  - gfortran
  - scikit-image
  - scikit-learn=0.23
  - cmocean
  - shapely
  - cartopy
  - pillow
  - descartes
  - xarray
  - pygmt
